# Generated by Django 5.0.6 on 2024-07-10 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cutomer',
            new_name='customer',
        ),
    ]
